# Generated by Django 2.1.4 on 2019-01-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readdetail',
            options={'ordering': ['-date']},
        ),
    ]
